### ISSUE TITLE
Error after phone number

### ISSUE THREAD

**Issue by ToxicFume** [NewSpring/rock-attended-checkin#10]
I just installed this through the Rock Shop and after I put in the phone number and hit search I receive this: 

> Exception Log:
NullReferenceException in Rock
Message
Object reference not set to an instance of an object.
Stack Trace
   at Rock.Workflow.Action.CheckIn.FilterGroupsBySpecialNeeds.Execute(RockContext rockContext, WorkflowAction action, Object entity, List`1& errorMessages)
   at Rock.Model.WorkflowAction.Process(RockContext rockContext, Object entity, List`1& errorMessages)
   at Rock.Model.WorkflowActivity.Process(RockContext rockContext, Object entity, List`1& errorMessages)
   at Rock.Model.Workflow.ProcessActivity(RockContext rockContext, DateTime processStartTime, Object entity, List`1& errorMessages)
   at Rock.Model.Workflow.ProcessActivities(RockContext rockContext, Object entity, List`1& errorMessages)
   at Rock.Model.WorkflowService.Process(Workflow workflow, Object entity, List`1& errorMessages)
   at Rock.CheckIn.CheckInBlock.ProcessActivity(String activityName, List`1& errorMessages)
   at RockWeb.Plugins.cc_newspring.AttendedCheckin.FamilySelect.ProcessPeople(CheckInFamily selectedFamily) in c:\inetpub\wwwroot\Plugins\cc_newspring\AttendedCheckin\FamilySelect.ascx.cs:line 845
   at RockWeb.Plugins.cc_newspring.AttendedCheckin.FamilySelect.OnLoad(EventArgs e) in c:\inetpub\wwwroot\Plugins\cc_newspring\AttendedCheckin\FamilySelect.ascx.cs:line 149
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by ToxicFume** [comment]
I had to go into workflows and assign the special needs attribute
